version: "3.4"

services:
    pgAdmin:
        restart: always
        image: dpage/pgadmin4
        ports:
            - "8000:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EAMIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        volumes:
            - pgadmin:/var/lib/pgadmin
    postgres:
        restart: always
        image: postgres
        container_name: "postgres_container"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - pgvol:/var/lib/postgresql/data
volumes:
    pgvol:
    pgadmin: 